### ISSUE TITLE
comment

### ISSUE THREAD

**Issue by timucindusunur** [KrashKrash/ECDSA-SECP256K1-Signature-Analysis-Tool#1]
=== ECDSA Signature Security Analysis Report ===
Timestamp: 2024-11-02 11:25:09.883503
Total Signatures Analyzed: 3
Vulnerable Signatures Found: 3

Detailed Vulnerability Analysis:

1. PARTIAL_NONCE_REUSE Vulnerability
   Affected Signatures: (0, 1)
   Severity: HIGH
   Shared Value: 0x83
   Description: Partial nonce reuse detected between signatures 0 and 1. Sharing 131 bits. r1 = 0xafe9a140f6974411911f1a15c743737c38398d838d5d8b911514d809afd4882d, r2 = 0x49b5b6d9f6247ee0cb087e0311b4a591a8fa99fdfc99820f091248c423056fe4

2. PARTIAL_NONCE_REUSE Vulnerability
   Affected Signatures: (0, 2)
   Severity: HIGH
   Shared Value: 0x7e
   Description: Partial nonce reuse detected between signatures 0 and 2. Sharing 126 bits. r1 = 0xafe9a140f6974411911f1a15c743737c38398d838d5d8b911514d809afd4882d, r2 = 0x1caa2537bd9ccffe735b71e5590fd18448d1d160ff7a801fa261a0839274da56

3. PARTIAL_NONCE_REUSE Vulnerability
   Affected Signatures: (1, 2)
   Severity: HIGH
   Shared Value: 0x82
   Description: Partial nonce reuse detected between signatures 1 and 2. Sharing 130 bits. r1 = 0x49b5b6d9f6247ee0cb087e0311b4a591a8fa99fdfc99820f091248c423056fe4, r2 = 0x1caa2537bd9ccffe735b71e5590fd18448d1d160ff7a801fa261a0839274da56

it gives these values ​​even for non-open signature values. Your only job is to make toys, you don't have any code that works!!!!!

**Comment by KrashKrash** [comment]
> === ECDSA Signature Security Analysis Report === Timestamp: 2024-11-02 11:25:09.883503 Total Signatures Analyzed: 3 Vulnerable Signatures Found: 3
> 
> Detailed Vulnerability Analysis:
> 
> 1. PARTIAL_NONCE_REUSE Vulnerability
>    Affected Signatures: (0, 1)
>    Severity: HIGH
>    Shared Value: 0x83
>    Description: Partial nonce reuse detected between signatures 0 and 1. Sharing 131 bits. r1 = 0xafe9a140f6974411911f1a15c743737c38398d838d5d8b911514d809afd4882d, r2 = 0x49b5b6d9f6247ee0cb087e0311b4a591a8fa99fdfc99820f091248c423056fe4
> 2. PARTIAL_NONCE_REUSE Vulnerability
>    Affected Signatures: (0, 2)
>    Severity: HIGH
>    Shared Value: 0x7e
>    Description: Partial nonce reuse detected between signatures 0 and 2. Sharing 126 bits. r1 = 0xafe9a140f6974411911f1a15c743737c38398d838d5d8b911514d809afd4882d, r2 = 0x1caa2537bd9ccffe735b71e5590fd18448d1d160ff7a801fa261a0839274da56
> 3. PARTIAL_NONCE_REUSE Vulnerability
>    Affected Signatures: (1, 2)
>    Severity: HIGH
>    Shared Value: 0x82
>    Description: Partial nonce reuse detected between signatures 1 and 2. Sharing 130 bits. r1 = 0x49b5b6d9f6247ee0cb087e0311b4a591a8fa99fdfc99820f091248c423056fe4, r2 = 0x1caa2537bd9ccffe735b71e5590fd18448d1d160ff7a801fa261a0839274da56
> 
> it gives these values ​​even for non-open signature values. Your only job is to make toys, you don't have any code that works!!!!!

I will make some toys... but before i do, can you explain a little further what are you talking about? i don't get it.

**Comment by KrashKrash** [comment]
> === ECDSA Signature Security Analysis Report === Timestamp: 2024-11-02 11:25:09.883503 Total Signatures Analyzed: 3 Vulnerable Signatures Found: 3
> 
> Detailed Vulnerability Analysis:
> 
> 1. PARTIAL_NONCE_REUSE Vulnerability
>    Affected Signatures: (0, 1)
>    Severity: HIGH
>    Shared Value: 0x83
>    Description: Partial nonce reuse detected between signatures 0 and 1. Sharing 131 bits. r1 = 0xafe9a140f6974411911f1a15c743737c38398d838d5d8b911514d809afd4882d, r2 = 0x49b5b6d9f6247ee0cb087e0311b4a591a8fa99fdfc99820f091248c423056fe4
> 2. PARTIAL_NONCE_REUSE Vulnerability
>    Affected Signatures: (0, 2)
>    Severity: HIGH
>    Shared Value: 0x7e
>    Description: Partial nonce reuse detected between signatures 0 and 2. Sharing 126 bits. r1 = 0xafe9a140f6974411911f1a15c743737c38398d838d5d8b911514d809afd4882d, r2 = 0x1caa2537bd9ccffe735b71e5590fd18448d1d160ff7a801fa261a0839274da56
> 3. PARTIAL_NONCE_REUSE Vulnerability
>    Affected Signatures: (1, 2)
>    Severity: HIGH
>    Shared Value: 0x82
>    Description: Partial nonce reuse detected between signatures 1 and 2. Sharing 130 bits. r1 = 0x49b5b6d9f6247ee0cb087e0311b4a591a8fa99fdfc99820f091248c423056fe4, r2 = 0x1caa2537bd9ccffe735b71e5590fd18448d1d160ff7a801fa261a0839274da56
> 
> it gives these values ​​even for non-open signature values. Your only job is to make toys, you don't have any code that works!!!!!

oh i seen it. its the false positive. i have updated it. thank you so much! if there are any issues that arises again, please do not hesitate to shut the fuck up and like i give a flying fuck to your
